In [7]:
import pandas as pd
import numpy as np
from numpy import asarray

from sklearn.preprocessing import OneHotEncoder
data = asarray([['red'], ['red'], ['yellow'], ['green'], ['yellow']])
print(data)
encoder = OneHotEncoder(sparse=False)
onehot = encoder.fit_transform(data)
print(onehot)


[['red']
 ['red']
 ['yellow']
 ['green']
 ['yellow']]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [10]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
lb = encoder.fit_transform(['red', 'red', 'yellow', 'green', 'yellow'])
print(lb)
#•	Sử dụng pandas:
#Ta cũng tạo ra 1 Series cho ví dụ trên và thực hiện mã hóa bằng pandas.
import pandas as pd
s = pd.Series(['red', 'red', 'yellow', 'green', 'yellow'])
s.astype('category').cat.codes


[1 1 2 0 2]


0    1
1    1
2    2
3    0
4    2
dtype: int8

In [14]:
#from sklearn.preprocessing import OrdinalEncoder
#from numpy import asarray
#enc = OrdinalEncoder()
#X = [['Male', 1], ['Female', 3], ['Female', 2]]
#enc.fit(X)
#OrdinalEncoder()
#enc.categories_[array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]
#enc.transform([['Female', 3], ['Male', 1]])

from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
X = [['Male', 1], ['Female', 3], ['Female', 2]]
print(enc.fit_transform(X))
enc.inverse_transform([[1, 0], [0, 1]])

[[1. 0.]
 [0. 2.]
 [0. 1.]]


array([['Male', 1],
       ['Female', 2]], dtype=object)

In [36]:
import pandas as pd
import numpy as np
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
# định nghĩa khoảng giá trị các nhóm
bins = [18, 25, 35, 60, 100]
# thực hiện rời rạc hóa
cats = pd.cut(ages, bins)
print(cats)
# lấy ra index của nhóm tương ứng với các phần tử
print(cats.codes)
# lấy ra các nhóm
print(cats.categories)
# thống kê số lượng phần tử ở mỗi nhóm
pd.value_counts(cats)
#ĐỒng nhất với ký hiệu toán học cho các khoảng, dấu ngoặc đơn,
# thay đổi phía bị đóng bằng cách truyền vào tham số right = False:[]-->[)
pd.cut(ages, [18, 26, 36, 61, 100], right=False)
# danh sách nhãn
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

pd.cut(ages, bins, labels=group_names)
# sinh dữ liệu ngẫu nhiên gồm 20 phần tử
data = np.random.rand(20)
cut_data = pd.cut(data, 4,precision = 2 ) #precision = 2 sẽ giới hạn độ chính xác thập phân ở hai chữ số.
cut_data
pd.value_counts(cut_data)
 



[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]
[0 0 0 1 0 0 2 1 3 2 2 1]
IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')


(0.67, 0.88]     8
(0.45, 0.67]     6
(0.021, 0.24]    3
(0.24, 0.45]     3
dtype: int64

In [37]:
import pandas as pd
import numpy as np
# sinh ngẫu nhiễn 1000 điểm dữ liệu
data2 = np.random.randn(1000)
# thực hiện hàm qcut trên dữ liệu vừa sinh ra
cats = pd.qcut(data2, 4)
cats
#thống kê số lượng phần tử
pd.value_counts(cats)
pd.qcut(data2, [0, 0.1, 0.5, 0.9, 1.])

[(1.352, 3.476], (1.352, 3.476], (0.0548, 1.352], (-3.362, -1.264], (0.0548, 1.352], ..., (1.352, 3.476], (-1.264, 0.0548], (0.0548, 1.352], (0.0548, 1.352], (-1.264, 0.0548]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.362, -1.264] < (-1.264, 0.0548] < (0.0548, 1.352] < (1.352, 3.476]]